### ISSUE TITLE
example中登陆授权问题

### ISSUE THREAD

**Issue by longtengdidu** [Ginshell/bongSDK-iOS#4]
在example工程登陆授权中，输入账号密码后，弹出个警告框提示授权成功，但是返回之前的授权页面，执行[bongSDK isAuthorizationValid]，却返回NO，这是为什么

**Comment by bzmario** [comment]
2.0 的 SDK 么？
ChenYu <notifications@github.com>于2015年8月13日 周四上午10:34写道：

**Comment by longtengdidu** [comment]
是的

**Comment by bzmario** [comment]
猜测可能是你没有在测试环境绑定设备，而之前的授权判断又多加了 `bongID` 的判断。

试下 [2.0 beta 2](https://github.com/Ginshell/bongSDK-iOS/releases/tag/v2.0-beta2)，已经把 `bongID` 的相关方法抽出来了，具体见 `Example` 示例

**Comment by longtengdidu** [comment]
新版本授权正常了
