### ISSUE TITLE
在自己的工程中请求授权时无法打开授权界面

### ISSUE THREAD

**Issue by longtengdidu** [Ginshell/bongSDK-iOS#5]
log信息：Warning: Attempt to present ***UINavigationController: 0x1256ae8b0*** on **RESideMenu: 0x12554c640** whose view is not in the window hierarchy!

是不是因为present的viewcontroller使用的UINavigationController不是新创建的，而是尝试从应用中获取的，进而导致的失败。。。

**Comment by longtengdidu** [comment]
Warning: Attempt to present <UINavigationController: 0x1256ae8b0> on <RESideMenu: 0x12554c640> whose view is not in the window hierarchy!

**Comment by bzmario** [comment]
这个 Nav 是 SDK 的么？

**Comment by longtengdidu** [comment]
RESideMenu的。。

**Comment by bzmario** [comment]
嗯...你是在问我非 `bongSDK` 相关的问题么？

**Comment by longtengdidu** [comment]
不是

**Comment by longtengdidu** [comment]
你在打开授权页面 是 类似这样写的么
[xxxx presentViewController:[[UINavigationController alloc] initWithRootViewController:xxVC] animated:YES completion:nil];

**Comment by longtengdidu** [comment]
通过日志信息看貌似你打开授权页面的到导航控制器是通过代码获取的上层viewcontroller的导航控制器，貌似是这样的

**Comment by bzmario** [comment]
SDK 授权界面是自建的 `UINavigationController` 包装的，`presentingViewController` 是 `keywindow` 的 `rootViewController`

**Comment by longtengdidu** [comment]
是类似这样的写法么，怎么也绕不过去，一直是之前的错误

[[UIApplication sharedApplication].keyWindow.rootViewController presentViewController:[[UINavigationController alloc] initWithRootViewController:loginVC] animated:YES completion:nil];

**Comment by longtengdidu** [comment]
这是别的SDK中的登陆方法 ，虽然用的是push  
- (void)login:(UINavigationController *)navController withAppKey:(NSString *)keyValue complition:(LoginBlock)block;


可不可以提供额外的方法让我传入自己的viewcontroller进行presentViewController

**Comment by bzmario** [comment]
你能提供一份可以重现这个问题的 demo 么？
ChenYu <notifications@github.com>于2015年8月14日 周五上午10:29写道：

**Comment by longtengdidu** [comment]
现在已经修改了自己的工程，可以正常运行了

之前问题可以在github.com/longtengdidu/RESideMenu重现，操作方法见readme文件

之前问题的原因是在被present出来的viewcontroller中使用keywindow.rootviewcontroller继续present新的viewcontroller

**Comment by bzmario** [comment]
OK
ChenYu <notifications@github.com>于2015年8月14日 周五上午11:44写道：
