### ISSUE TITLE
经常收不到通知

### ISSUE THREAD

**Issue by longtengdidu** [Ginshell/bongSDK-iOS#6]
还有就是得到这种错误信息几率很大 ，主要是什么原因 error: Error Domain=cn.bong.sdk.error Code=12 "bong X/XX 事件通知设置失败" UserInfo=0x170079180 {NSLocalizedDescription=bong X/XX 事件通知设置失败}

**Comment by longtengdidu** [comment]
还有就是得到这种错误信息几率很大 ，主要是什么原因  error: Error Domain=cn.bong.sdk.error Code=12 "bong X/XX 事件通知设置失败" UserInfo=0x170079180 {NSLocalizedDescription=bong X/XX 事件通知设置失败}

**Comment by bzmario** [comment]
你的 bong 有和 iOS 保持长连么?
